apiVersion: "stable.k8s.psg.io/v1"
kind: "Certificate"
metadata:
  name: "psg-dot-io"
  labels:
    stable.k8s.psg.io/kcm.class: "default"
spec:
  # you can override the acme endpoint from the deployment default
  acmeURL: https://acme-staging-v02.api.letsencrypt.org/directory
  domain: "psg.io"
  email: "admin@psg.io"
  provider: "googlecloud"
  secretName: cert-psg.io
